// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10299399_PROG7311_GreenEnergy_POE.Models;

#nullable disable

namespace ST10299399_PROG7311_GreenEnergy_POE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514120931_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ST10299399_PROG7311_GreenEnergy_POE.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeePassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeEmail = "admin1@gmail.com",
                            EmployeeName = "Admin1",
                            EmployeePassword = "admin1"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeEmail = "admin2@gmail.com",
                            EmployeeName = "Admin2",
                            EmployeePassword = "admin2"
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmployeeEmail = "admin3@gmail.com",
                            EmployeeName = "Admin3",
                            EmployeePassword = "admin3"
                        },
                        new
                        {
                            EmployeeId = 4,
                            EmployeeEmail = "admin4@gmail.com",
                            EmployeeName = "Admin4",
                            EmployeePassword = "admin4"
                        },
                        new
                        {
                            EmployeeId = 5,
                            EmployeeEmail = "admin5@gmail.com",
                            EmployeeName = "Admin5",
                            EmployeePassword = "admin5"
                        });
                });

            modelBuilder.Entity("ST10299399_PROG7311_GreenEnergy_POE.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FarmerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerSurname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            FarmerId = 1,
                            FarmerEmail = "pieter@gmail.com",
                            FarmerName = "Pieter",
                            FarmerPassword = "pieter123",
                            FarmerPhone = "1234567890",
                            FarmerSurname = "Visser"
                        },
                        new
                        {
                            FarmerId = 2,
                            FarmerEmail = "john@gmail.com",
                            FarmerName = "John",
                            FarmerPassword = "john123",
                            FarmerPhone = "0647512222",
                            FarmerSurname = "Porker"
                        },
                        new
                        {
                            FarmerId = 3,
                            FarmerEmail = "jasper@gmail.com",
                            FarmerName = "Jasper",
                            FarmerPassword = "jasper123",
                            FarmerPhone = "0761595555",
                            FarmerSurname = "Rasper"
                        },
                        new
                        {
                            FarmerId = 4,
                            FarmerEmail = "manie@gmail.com",
                            FarmerName = "Manie",
                            FarmerPassword = "manie123",
                            FarmerPhone = "0541235678",
                            FarmerSurname = "Libbok"
                        },
                        new
                        {
                            FarmerId = 5,
                            FarmerEmail = "fanie@gmail.com",
                            FarmerName = "Fanie",
                            FarmerPassword = "fanie123",
                            FarmerPhone = "0671592345",
                            FarmerSurname = "Bosveld"
                        });
                });

            modelBuilder.Entity("ST10299399_PROG7311_GreenEnergy_POE.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ST10299399_PROG7311_GreenEnergy_POE.Models.Product", b =>
                {
                    b.HasOne("ST10299399_PROG7311_GreenEnergy_POE.Models.Farmer", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("ST10299399_PROG7311_GreenEnergy_POE.Models.Farmer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
